<?php
/**
 * The template for displaying all pages.
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site will use a
 * different template.
 *
 * Please see /external/starkers-utilities.php for info on Starkers_Utilities::get_template_parts()
 *
 * @package 	WordPress
 * @subpackage 	Starkers
 * @since 		Starkers 4.0
 */
?>
<?php Starkers_Utilities::get_template_parts( array( 'parts/shared/html-header', 'parts/shared/header' ) ); ?>

<main id="main" class="main" role="main">
    <?php // if ( have_posts() ) while ( have_posts() ) : the_post(); ?>
    <?php // the_content(); ?>
    <?php // endwhile; ?>

    <section class="about">
        <section class="intro">
            <p>i-DAT is developing a range of ‘Operating Systems’ to dynamically manifest ‘data’ as experience in order to enhance perspectives on a complex world. The Operating Systems project explores data as an abstract and invisible material that generates a dynamic mirror image of our biological, ecological and social activities.</p>
            <p>The Operating Systems project proposes a range of tools and initiatives that have the potential to enhance our ability to perceive and orchestrate this mirror world. The intention with the range of Operating Systems outlined on this site is to make the data generated by human and ecological activity tangible and readily available to the public, artists, engineers and scientists.</p>
        </section>

        <section class="quote">
            <blockquote>Idly, he wondered what these geometric forms really represented - he knew that only a few seconds earlier they had constituted an immediately familiar part of his everyday existence - but however he rearranged them spatially in his mind, or sought their associations, they still remained a random assembly of geometric forms.</blockquote>
            <small class="author">Ballard, JG</small>
        </section>
    </section>

    <section class="os-gallery">

        <div class="os eco-os">
            <h3>Eco-OS</h3>
            <a href="http://eco-os.<?php echo str_replace('http://', '', site_url())?>" class="icon"></a>
        </div>

        <div class="os arch-os">
            <h3>Arch-OS</h3>
            <a href="http://arch-os.<?php echo str_replace('http://', '', site_url())?>" class="icon"></a>
        </div>

        <div class="os bio-os">
            <h3>Bio-OS</h3>
            <a href="http://bio-os.<?php echo str_replace('http://', '', site_url())?>" class="icon"></a>
        </div>

        <div class="os dome-os">
            <h3>Dome-OS</h3>
            <a href="http://dome-os.<?php echo str_replace('http://', '', site_url())?>" class="icon"></a>
        </div>

        <div class="os s-os">
            <h3>S-OS</h3>
            <a href="http://s-os.<?php echo str_replace('http://', '', site_url())?>" class="icon"></a>
        </div>
    </section>
</main>

<?php Starkers_Utilities::get_template_parts( array( 'parts/shared/footer','parts/shared/html-footer' ) ); ?>